In [22]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [23]:
### Load ANN tarined model
# Scaler, pickle and onehot encoder

In [24]:
model = load_model('model.h5')

with open('lable_encoder_gender.pkl', 'rb') as file:
    lable_encoder_geo = pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb') as file:
    one_hot_encoder_geo = pickle.load(file)

with open("scaler_X_train.pkl", 'rb') as file:
    scaler = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [39]:
input_data = {
'CreditScore': 600,
'Geography': 'France',
'Gender': 'Male',
'Age': 40,
'Tenure': 3,
'Balance': 60000,
'NumOfProducts': 2,
'HasCrCard': 1,
'IsActiveMember': 1,
'EstimatedSalary': 50000
}

In [40]:
print(one_hot_encoder_geo.categories_)

[array(['France', 'Germany', 'Spain'], dtype=object)]

In [41]:
geo_encoded = one_hot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\SwastiPradhan\Desktop\GenAI\myenv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [43]:
input_df = pd.DataFrame([input_data])

input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [57]:
input_data = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df], axis=1)
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [58]:
input_data['Gender'] = lable_encoder_geo.transform(input_data['Gender'])
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [60]:
input_scaler = scaler.transform(input_data)

input_scaler

array([[-0.47154541,  0.90911166,  0.09477172, -0.69844549, -0.29010416,
         0.80510537,  0.63367318,  0.95214374, -0.84805047,  0.98019606,
        -0.57581067, -0.56349184]])

In [61]:
prediction = model.predict(input_scaler)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step

In [62]:
prediction

array([[0.02405899]], dtype=float32)

In [63]:
prediction_prob = prediction[0][0]
prediction_prob

np.float32(0.024058986)

In [64]:
if prediction_prob>0.5:
    print('likely to churn')
else:
    print('not likely to churn')

not likely to churn